#ifndef RANDOMIZER_CONSTANTS_H
#define RANDOMIZER_CONSTANTS_H

#include "macros.h"

#define MINOR_LOCATION_COUNT 100

MAKE_ENUM(u8, ItemSource)
{
    ITEM_SOURCE_LONG_BEAM,
    ITEM_SOURCE_CHARGE_BEAM,
    ITEM_SOURCE_ICE_BEAM,
    ITEM_SOURCE_WAVE_BEAM,
    ITEM_SOURCE_PLASMA_BEAM,
    ITEM_SOURCE_BOMBS,
    ITEM_SOURCE_VARIA_SUIT,
    ITEM_SOURCE_GRAVITY_SUIT,
    ITEM_SOURCE_MORPH_BALL,
    ITEM_SOURCE_SPEED_BOOSTER,
    ITEM_SOURCE_HI_JUMP,
    ITEM_SOURCE_SCREW_ATTACK,
    ITEM_SOURCE_SPACE_JUMP,
    ITEM_SOURCE_POWER_GRIP,
    ITEM_SOURCE_FULLY_POWERED,
    ITEM_SOURCE_ZIPLINES,

    ITEM_SOURCE_COUNT
};

MAKE_ENUM(u8, RandoItemType) {
    RIT_NONE,
    RIT_ENERGY_TANK,
    RIT_MISSILE_TANK,
    RIT_SUPER_MISSILE_TANK,
    RIT_POWER_BOMB_TANK,
    RIT_LONG_BEAM,
    RIT_CHARGE_BEAM,
    RIT_ICE_BEAM,
    RIT_WAVE_BEAM,
    RIT_PLASMA_BEAM,
    RIT_BOMBS,
    RIT_VARIA_SUIT,
    RIT_GRAVITY_SUIT,
    RIT_MORPH_BALL,
    RIT_SPEED_BOOSTER,
    RIT_HI_JUMP,
    RIT_SCREW_ATTACK,
    RIT_SPACE_JUMP,
    RIT_POWER_GRIP,
    RIT_FULLY_POWERED,
    RIT_ZIPLINES,
    RIT_INFANT_METROID,
};

MAKE_ENUM(u8, RandoItemSprite) {
    RIS_EMPTY,
    RIS_ENERGY_TANK,
    RIS_MISSILE_TANK,
    RIS_SUPER_MISSILE_TANK,
    RIS_POWER_BOMB_TANK,
    RIS_LONG_BEAM,
    RIS_CHARGE_BEAM,
    RIS_ICE_BEAM,
    RIS_WAVE_BEAM,
    RIS_PLASMA_BEAM,
    RIS_BOMBS,
    RIS_VARIA_SUIT,
    RIS_GRAVITY_SUIT,
    RIS_MORPH_BALL,
    RIS_SPEED_BOOSTER,
    RIS_HI_JUMP,
    RIS_SCREW_ATTACK,
    RIS_SPACE_JUMP,
    RIS_POWER_GRIP,
    RIS_FULLY_POWERED,
    RIS_ZIPLINES,
    RIS_INFANT_METROID,
    RIS_ANONYMOUS,
    RIS_SHINY_MISSILE_TANK,
    RIS_SHINY_POWER_BOMB_TANK,
};

MAKE_ENUM(u8, RandoItemJingle) {
    RIJ_DEFAULT,
    RIJ_MINOR,
    RIJ_MAJOR,
    RIJ_UNKNOWN,
    RIJ_FULLY_POWERED,
};

MAKE_ENUM(u8, DifficultyOptions) {
    DIFF_OPT_UNCHANGED,
    DIFF_OPT_ALL,
    DIFF_OPT_EASY_NORMAL,
    DIFF_OPT_HARD
};

#endif // RANDOMIZER_CONSTANTS_H
